services:
  web:
    build:
      context: .
      dockerfile: php.Dockerfile
    container_name: my-web-kpwm
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    networks:
      - my-network-kpwm

  db:
    image: mysql:8.0
    container_name: my-db-kpwm
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cruddb
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data-kpwm:/var/lib/mysql
    networks:
      - my-network-kpwm

volumes:
  db_data-kpwm:


networks:
  my-network-kpwm: